# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cumprod_interface <- function(in_vec) {
    .Call('_cumprod_cumprod_interface', PACKAGE = 'cumprod', in_vec)
}

